collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "main"

title: Codemantn
description: > # this means to ignore newlines until "baseurl:"
  I am HSPO Developer
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Author Settings
author: Ban Nguyen # add your name
author-img: laban.png # add your photo
about-author: Always hungry to keep learning. # add description
social-facebook: simpleBAN # add your Facebook handle
social-linkedin: bannv # add your Linkedin handle
social-email: codemantn@gmail.com
social-github: LaBanHSPO

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"